title: ARCADE

description: Agent-based Representation of Cells And Dynamic Environments

theme: just-the-docs

url: https://bagherilab.github.io/ARCADE/

baseurl: ARCADE

repository: bagherilab/ARCADE

math: mathjax

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  publications:
    output: false
  changelog:
    output: false

plugins:
  - jekyll-github-metadata

callouts:
  warning:
    title: Warning
    color: red
