name: documentation

on:
  push:
    branches:
      - main
      - develop

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Generate javadoc
      run: |
        ./gradlew javadoc
        touch docs/javadoc/.nojekyll

    - name: Publish docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/javadoc
        clean-exclude: |
          _badges
          _coverage

    - name: Extract project version
      run: |
        echo "VERSION=$(grep -oP 'version = "\K([0-9\.]+)(?=")' build.gradle)" >> $GITHUB_ENV

    - name: Generate version badge
      uses: knightdave/anybadge-action@v1.1.0
      with:
        file: docs/_badges/version.svg
        label: version
        value: v${{ env.VERSION }}
        color: teal
        template: docs/_badges/template.svg
        overwrite: true

    - name: Generate license badge
      uses: knightdave/anybadge-action@v1.1.0
      with:
        file: docs/_badges/license.svg
        label: license
        value: BSD-3-Clause
        color: yellowgreen
        template: docs/_badges/template.svg
        overwrite: true

    - name: Generate passing badge
      if: success()
      uses: knightdave/anybadge-action@v1.1.0
      with:
        file: docs/_badges/documentation.svg
        label: docs
        value: passing
        color: green
        template: docs/_badges/template.svg
        overwrite: true

    - name: Generate failing badge
      if: failure()
      uses: knightdave/anybadge-action@v1.1.0
      with:
        file: docs/_badges/documentation.svg
        label: docs
        value: failing
        color: red
        template: docs/_badges/template.svg
        overwrite: true

    - name: Publish badge
      if: success() || failure()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/_badges
        target-folder: _badges
        clean: false
